name: tsec_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#android
# version: 2.0.0+18
#ios
version: 1.0.2+2

environment:
  sdk: ">=2.17.0 <=4.0.0"


dependencies:
  showcaseview: ^3.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.5
  date_picker_timeline: ^1.2.3
  expandable: ^5.0.1
  file_picker: ^5.3.1
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  firebase_storage: ^11.0.7
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_riverpod: ^1.0.4
  get_it: ^7.2.0
  # go_router: ^3.1.1
  go_router: ^11.1.2
  image_picker: ^1.0.0
  intl: ^0.19.0
  json_annotation: ^4.6.0
  lottie: ^2.3.2
  open_file: ^3.2.1
  path_provider: ^2.1.4
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  textfield_search: ^0.10.0
  top_snackbar_flutter: ^1.1.1
  url_launcher: ^6.1.4
  dropdown_search: ^5.0.6
  autocomplete_textfield: ^2.0.1
  animations: ^2.0.8
  equatable: ^2.0.5
  dio: ^5.4.1
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.12.0
  flutter_blurhash: ^0.6.0
  easy_stepper: ^0.8.0
  flutter_local_notifications: ^17.2.1+1
  #firebase_ui_firestore: ^1.6.3
  bcrypt: ^1.1.3
  shimmer_animation: ^2.0.0

dev_dependencies:
  build_runner: null
#  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3

flutter_icons:
  image_path: "assets/images/icons/tsecAppIcon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/
    - assets/data/faculty_details/
    - assets/data/about_department/
    - assets/data/curriculum_data/
    - assets/images/themes/
    - assets/images/app_bar/
    - assets/images/new_app_bar/
    - assets/images/branches/
    - assets/images/icons/
    - assets/images/coming_soon/
    - assets/images/pfpholder.jpg
    - assets/images/tsecImages.png
    - assets/images/tsecimage.png
    - assets/images/tsecimage2.png
    - assets/images/railwayConcession.png
    - assets/images/devs.png
    - assets/images/devs-dark.png
    - assets/images/tick2.png
    - assets/images/railway.png
    - assets/images/attendance.png
    - assets/icons/
    - assets/animation/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-VariableFont_wght.ttf          
    - family: Priego 
      fonts:
        - asset: assets/fonts/priego-extrabold.otf
          weight: 800
        - asset: assets/fonts/priego-bold.otf
          weight: 700 
        - asset: assets/fonts/priego-semibold.otf
          weight: 600 
        - asset: assets/fonts/priego-medium.otf
          weight: 500 
        - asset: assets/fonts/priego-regular.otf
          weight: 400 
    - family: Inter 
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600 
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500 
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400 
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages